export const puppyList = [
    {
      id: 1,
      name: "Sir Waggington",
      email: "sir-wag@email.com",
      isCute: true,
      age: 5,
      ownerId: 1,
      photo: 'https://www.dailydogdiscoveries.com/wp-content/uploads/2016/02/wagging-tail.png',
      tricks: [
        { id: 2, title: "Lay Down" },
        { id: 3, title: "Jump through flaming hoop" },
      ],
    },
    {
      id: 2,
      name: "Fiona Penny Pickles",
      email: "pick-your-pennies@email.com",
      isCute: true,
      age: 6,
      ownerId: 1,
      photo: 'https://media.istockphoto.com/photos/aggressive-angry-dog-picture-id542218056?k=6&m=542218056&s=612x612&w=0&h=jSawPE-i2QHM-6i1YVCiDfuu4nFSTcAlvuIepnIUFk0=',
      tricks: [],
    },
    {
      id: 3,
      name: "Professor Wagglesworth",
      email: "waggie@email.com",
      isCute: true,
      age: 6,
      ownerId: 2,
      photo: 'https://i.huffpost.com/gen/1179372/images/o-DOG-GLASSES-facebook.jpg',
      tricks: [{ id: 1, title: "Sit" }],
    },
    {
      id: 4,
      name: "Sergeant Barkowitz",
      email: "the-sarge@email.com",
      isCute: true,
      age: 4,
      ownerId: 2,
      photo: 'https://i.pinimg.com/originals/70/94/0d/70940d16feda853ef2e86f127ff4bbb7.jpg',
      tricks: [{ id: 2, title: "Lay Down" }],
    },
    {
      id: 5,
      name: "Captain Sniffer",
      email: "capn-sniff@email.com",
      isCute: true,
      age: 7,
      ownerId: 3,
      photo: 'https://i.redd.it/1uw76vge45i41.jpg',
      tricks: [],
    },
    {
      id: 6,
      name: "Miss Furbulous",
      email: "miss-furby@email.com",
      isCute: true,
      age: 1,
      ownerId: 3,
      photo: 'https://i.pinimg.com/736x/4f/64/ba/4f64ba1c7f17f1cc5ab38029f224189a.jpg',
      tricks: [],
    },
    {
      id: 7,
      name: "Alfred von Wigglebottom",
      email: "alfie@email.com",
      isCute: true,
      age: 2,
      ownerId: 3,
      photo: 'https://i.imgflip.com/1u0wd1.jpg',
      tricks: [],
    },
  ];